### ISSUE TITLE
Feature: Inline comments

### ISSUE THREAD

**Issue by Arpita-Jaiswal** [fastn-stack/fastn#958]
Currently, we add comments using `;;` at the beginning of the line in fastn language.
We need to extend this feature to be used inline.

### Case 1
```ftd
-- ftd.text: Hello      ;; displays the hello
```
The Output should be:
```
Hello
```
This should also be working.

### Case 2
We can escape the comments inline by using `\`.

```ftd
-- ftd.text: Hello      \;; displays the hello
```
The Output should be:
```
Hello      ;; displays the hello
```

### Case 3
We can also escape `\`.
```ftd
-- ftd.text: Hello      \\;; displays the hello
```
The Output should be:
```
Hello      \;; displays the hello
```

**Comment by harshdoesdev** [comment]
So, there are two ways to start a comment:
/-- for commenting out sections
; for commenting a single line or part of line (not implemented yet)

I found that the /-- comments are being ignored by the interpreter, while the ; are ignored by the parser itself. ; can be escaped using \ if we want to use that character. So we have to check if a line contains a ;, if yes, then we will have to check if it is not preceded by any \, if it is preceded by a backslash, we will count it as a normal text, and then check again if the string contains any other ;, if yes then repeat the loop, if not then the string does not have any inline comments. But if it was not preceded by any \, then we will split at this index and return the left hand-side string.

Is it a nice approach to this problem?

**Comment by harshdoesdev** [comment]
This issue can be closed because I have implemented the inline comments feature in this PR. Currently, we have used ;; in many places as a marker for highlighting HTML (Refer: HTML test 52) in FTD, which is why some tests are failing. We would need to find a new syntax for that marker because they are syntactically the same and cannot be distinguished without some expensive operations. They have been extensively used in fastn.com, so we need to replace them there first.

Here is the PR:
https://github.com/fastn-stack/fastn/pull/1077
